apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eoj612u7t-nodejs 
  janus-idp.io/tekton: eoj612u7t-nodejs
  backstage.io/kubernetes-id: eoj612u7t-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eoj612u7t-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  