apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eoj612u7t-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eoj612u7t-nodejs 
  name: eoj612u7t-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: eoj612u7t-nodejs 
